apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-config
  namespace: wp-mysql-stack
data:
  WORDPRESS_DB_HOST: wp-db
  WORDPRESS_DB_USER: root
  WORDPRESS_DB_NAME: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-web
  namespace: wp-mysql-stack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wp-web
  template:
    metadata:
      labels:
        app: wp-web
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: wp-config
                  key: WORDPRESS_DB_HOST
            - name: WORDPRESS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: wp-config
                  key: WORDPRESS_DB_USER
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-db-secret
                  key: root-password
            - name: WORDPRESS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: wp-config
                  key: WORDPRESS_DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: wp-web
  namespace: wp-mysql-stack
spec:
  type: NodePort
  selector:
    app: wp-web
  ports:
    - port: 80
      targetPort: 80
